version: "3"

services:
  api:
    build: .
    image: create_quiz-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=susel
